// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkqTaeUIQneXSXsl0hgYcGTH-2SoLLaI',
    appId: '1:805640359232:web:97fd32ef2cd2c94f083ea5',
    messagingSenderId: '805640359232',
    projectId: 'doggy-date-ba90d',
    authDomain: 'doggy-date-ba90d.firebaseapp.com',
    storageBucket: 'doggy-date-ba90d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFcOQdj49lmAQ55ifdfLjzcjiajySBjg',
    appId: '1:805640359232:android:9a67497a57325602083ea5',
    messagingSenderId: '805640359232',
    projectId: 'doggy-date-ba90d',
    storageBucket: 'doggy-date-ba90d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPSpFGydjrJktXo0UoxoR7BkP5q_x3ArM',
    appId: '1:805640359232:ios:94edf7332e14afac083ea5',
    messagingSenderId: '805640359232',
    projectId: 'doggy-date-ba90d',
    storageBucket: 'doggy-date-ba90d.appspot.com',
    iosClientId: '805640359232-gjevnh7casli7h1qjk84r900gu38ortv.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggyDate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPSpFGydjrJktXo0UoxoR7BkP5q_x3ArM',
    appId: '1:805640359232:ios:94edf7332e14afac083ea5',
    messagingSenderId: '805640359232',
    projectId: 'doggy-date-ba90d',
    storageBucket: 'doggy-date-ba90d.appspot.com',
    iosClientId: '805640359232-gjevnh7casli7h1qjk84r900gu38ortv.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggyDate',
  );
}
