// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhPkJhgF9P0rCg4EPvC-c8h-BXf7v8JY',
    appId: '1:452423477297:web:7105a89b60afb6c7504d10',
    messagingSenderId: '452423477297',
    projectId: 'doggy-date-bb9d5',
    authDomain: 'doggy-date-bb9d5.firebaseapp.com',
    storageBucket: 'doggy-date-bb9d5.appspot.com',
    measurementId: 'G-W26SQJZKJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PE-1nzKPKSFzyZBIuwnd3PAEcWr4f7s',
    appId: '1:452423477297:android:95cccb67e7906eb0504d10',
    messagingSenderId: '452423477297',
    projectId: 'doggy-date-bb9d5',
    storageBucket: 'doggy-date-bb9d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPrfs9asSdli7Lb6Cp4Gbso8fwYSo7SM',
    appId: '1:452423477297:ios:b2d271e4f6abc3d1504d10',
    messagingSenderId: '452423477297',
    projectId: 'doggy-date-bb9d5',
    storageBucket: 'doggy-date-bb9d5.appspot.com',
    iosClientId: '452423477297-man2793a81cr9qbu5hdvlamf5t14r1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggyDate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgPrfs9asSdli7Lb6Cp4Gbso8fwYSo7SM',
    appId: '1:452423477297:ios:b2d271e4f6abc3d1504d10',
    messagingSenderId: '452423477297',
    projectId: 'doggy-date-bb9d5',
    storageBucket: 'doggy-date-bb9d5.appspot.com',
    iosClientId: '452423477297-man2793a81cr9qbu5hdvlamf5t14r1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggyDate',
  );
}
